// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQNmsEhowa4rEoNoRgn42VINmu8rdAyc',
    appId: '1:296555067625:web:48725f95893248ba1a5878',
    messagingSenderId: '296555067625',
    projectId: 'rental-8305f',
    authDomain: 'rental-8305f.firebaseapp.com',
    storageBucket: 'rental-8305f.appspot.com',
    measurementId: 'G-73Y4CN4DKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRV3iHZ4_npCdqIn6R7Pg1NhGMH-YLTI',
    appId: '1:296555067625:android:05aa8fc3b758624d1a5878',
    messagingSenderId: '296555067625',
    projectId: 'rental-8305f',
    storageBucket: 'rental-8305f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBU1fAaCQJKcSrOXMWqyWG6L7YEnkzP7g',
    appId: '1:296555067625:ios:e2d587e23222ff0a1a5878',
    messagingSenderId: '296555067625',
    projectId: 'rental-8305f',
    storageBucket: 'rental-8305f.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBU1fAaCQJKcSrOXMWqyWG6L7YEnkzP7g',
    appId: '1:296555067625:ios:44bd9210dfe7874c1a5878',
    messagingSenderId: '296555067625',
    projectId: 'rental-8305f',
    storageBucket: 'rental-8305f.appspot.com',
    iosBundleId: 'com.example.rentalApp.RunnerTests',
  );
}
